// apps/client-qwik/src/components/modal/transactions/DeleteTransactionModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, $ } from '@builder.io/qwik'
import type { TransactionDTO } from 'shared-types'
import { Modal } from '../Modal'
import { useDeleteTransaction } from '~/api/transactionsAPI'

type DeleteTransactionModalProps = {
  transaction: TransactionDTO
  open: QRL<() => void>
  close: QRL<() => void>
}

export const DeleteTransactionModal = component$(
  ({ transaction, close }: DeleteTransactionModalProps) => {
    const deleteTransaction = useDeleteTransaction()
    const handleConfirm = $(async () => {
      deleteTransaction.submit({ id: transaction._id })
      close()
    })

    const handleCancel = $(() => {
      close()
    })

    return (
      <Modal
        title="Usuwanie transakcji"
        subtitle={transaction.title}
        handleConfirm={handleConfirm}
        handleCancel={handleCancel}
      >
        Czy na pewno chcesz usunąć transakcję {transaction.title}?
      </Modal>
    )
  }
)

// apps/client-react/src/components/modal/transaction/DeleteTransactionModal.tsx
import { ModalProps, TransactionDTO } from 'shared-types'
import ModalHeader from '../sections/ModalHeader'
import Modal from '../Modal'
import ModalFooter from '../sections/ModalFooter'
import { toast } from 'react-toastify'
import { useDeleteTransactionMutation } from '../../../redux/api/slices/transactionSlice'

type DeleteTransactionModalProps = {
  transaction: TransactionDTO
}

const DeleteTransactionModal = ({
  open,
  handleClose,
  transaction
}: DeleteTransactionModalProps & ModalProps) => {
  const [deleteTransaction] = useDeleteTransactionMutation()

  const handleConfirm = () => {
    deleteTransaction(transaction._id)
      .unwrap()
      .then(() => {
        toast.success('Transakcja została usunięta pomyślnie!', {
          position: 'bottom-right',
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: 'colored'
        })
        handleClose()
      })
      .catch(() => {
        toast.warn('Nie udało się usunąć transakcji.', {
          position: 'bottom-right',
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: 'colored'
        })
      })
  }

  return (
    <>
      {open && (
        <Modal handleClose={handleClose}>
          <ModalHeader
            handleClose={handleClose}
            title={'Usuwanie transakcji'}
            subtitle={transaction?.title}
          />
          <ModalFooter handleClose={handleClose} handleConfirm={handleConfirm} />
        </Modal>
      )}
    </>
  )
}

export default DeleteTransactionModal
