// apps/client-qwik/src/components/modal/transactions/EditTransactionModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, $, useStore } from '@builder.io/qwik'
import type { AccountDTO, TransactionDTO, TransactionStatus } from 'shared-types'
import { Modal } from '../Modal'
import { useEditTransaction } from '~/api/transactionsAPI'
import { useCategories } from '~/api/categoriesAPI'

type EditTransactionModalProps = {
  account: AccountDTO
  transaction: TransactionDTO
  open: QRL<() => void>
  close: QRL<() => void>
}

type StatusOption = {
  id: number
  value: TransactionStatus
  name: string
}

const statuses: StatusOption[] = [
  {
    id: 0,
    value: 'FINISHED',
    name: 'Opłacona'
  },
  {
    id: 1,
    value: 'PENDING',
    name: 'Oczekująca'
  }
]

export const EditTransactionModal = component$(
  ({ account, transaction, close }: EditTransactionModalProps) => {
    const editTransaction = useEditTransaction()

    const handleCancel = $(() => {
      close()
    })

    const categories = useCategories().value.filter((c) => c.categoryType === 'TRANSACTION')

    const state = useStore({
      categoryId: categories.find((c) => c.id === transaction.categoryId)?.id,
      status: transaction.status,
      recipient: transaction.recipient,
      title: transaction.title,
      value: transaction.value,
      isExpense: transaction.isExpense,
      isRecurring: transaction.isRecurring,
      date: transaction.date,
      description: transaction.description
    })

    const handleConfirm = $(async () => {
      const newTransaction: Partial<TransactionDTO> = {
        ...transaction,
        accountId: account._id,
        categoryId: state.categoryId,
        status: state.status as TransactionStatus,
        recipient: state.recipient,
        title: state.title,
        value: state.value,
        isExpense: state.isExpense,
        isRecurring: state.isRecurring,
        date: state.date,
        description: state.description
      }
      await editTransaction.submit(newTransaction)
      close()
    })

    //   function handleOpenCategoriesMenu() {
    //     close()
    //     //   isCategoryMenuOpen.value = true
    //   }

    //   function handleCloseCategoriesMenu() {
    //     open()
    //     //   isCategoryMenuOpen.value = false
    //   }

    return (
      <>
        <Modal title="Nowe konto" handleConfirm={handleConfirm} handleCancel={handleCancel}>
          <div class="flex flex-col gap-1">
            <label for="account-category-select">Kategoria</label>
            <select
              value={state.categoryId}
              onChange$={(e) => (state.categoryId = (e.target as HTMLSelectElement).value)}
            >
              {categories.map((c) => (
                <option value={c.id} key={`category-select-option-${c.id}`}>
                  {c.name}
                </option>
              ))}
            </select>
          </div>

          {/* STATUS */}
          <div class="flex flex-col gap-1">
            <label for="account-category-select">Kategoria</label>
            <select
              value={state.status}
              onChange$={(e) =>
                (state.status = (e.target as HTMLSelectElement).value as TransactionStatus)
              }
            >
              {statuses.map((c) => (
                <option value={c.value} key={`status-select-option-${c.id}`}>
                  {c.name}
                </option>
              ))}
            </select>
          </div>

          {/* ODBIORCA */}
          <div class="flex flex-col gap-1">
            <label for="transaction-recipient-input">Odbiorca</label>
            <input
              id="transaction-recipient-input"
              type="text"
              value={state.recipient}
              onInput$={(e) => (state.recipient = (e.target as HTMLInputElement).value)}
            />
          </div>

          {/* TYTUŁ */}
          <div class="flex flex-col gap-1">
            <label for="transaction-title-input">Nazwa</label>
            <input
              id="transaction-title-input"
              type="text"
              value={state.title}
              onInput$={(e) => (state.title = (e.target as HTMLInputElement).value)}
            />
          </div>

          {/* WARTOŚĆ */}
          <div class="flex flex-col gap-1">
            <label for="transaction-value-input">Wartość</label>
            <input
              id="transaction-value-input"
              type="number"
              value={state.value}
              onInput$={(e) => (state.value = +(e.target as HTMLInputElement).value)}
            />
          </div>

          {/* WYDATEK */}
          <div class="flex flex-row gap-2">
            <input
              id="transaction-expense-checkbox"
              type="checkbox"
              checked={state.isExpense}
              onInput$={(e) => (state.isExpense = (e.target as HTMLInputElement).checked)}
            />
            <label for="transaction-expense-checkbox">Wydatek</label>
          </div>

          {/* TRANSAKCJA CYKLICZNA */}
          <div class="flex flex-row gap-2">
            <input
              id="transaction-recurring-checkbox"
              type="checkbox"
              checked={state.isRecurring}
              onInput$={(e) => (state.isRecurring = (e.target as HTMLInputElement).checked)}
            />
            <label for="transaction-recurring-checkbox">Transakcja cykliczna</label>
          </div>

          {/* DATA */}
          <div class="flex flex-col gap-1">
            <label for="transaction-date-input">Data</label>
            <input
              id="transaction-date-input"
              type="date"
              value={state.date}
              onInput$={(e) => (state.date = (e.target as HTMLInputElement).value)}
            />
          </div>
          {/* OPIS */}
          <div class="flex flex-col gap-1">
            <label for="transaction-description-input">Opis</label>
            <input
              id="transaction-description-input"
              type="text"
              value={state.description}
              onInput$={(e) => (state.description = (e.target as HTMLInputElement).value)}
            />
          </div>
        </Modal>
      </>
    )
  }
)

// apps/client-react/src/components/modal/transaction/EditTransactionModal.tsx
import { ModalProps, TransactionDTO, TransactionStatus } from 'shared-types'
import Modal from '../Modal'
import ModalFooter from '../sections/ModalFooter'
import ModalHeader from '../sections/ModalHeader'
import { useReducer, useState } from 'react'
import Input from '../../inputs/Input'
import Checkbox from '../../inputs/Checkbox'
import SelectDate from '../../inputs/SelectDate'
import TextArea from '../../inputs/TextArea'
import Select from '../../inputs/Select'
import { Option } from '../../inputs/Select'
import SelectCategory from '../../inputs/SelectCategory'
import ManageCategoriesModal from '../ManageCategoriesModal'
import { useEditTransactionMutation } from '../../../redux/api/slices/transactionSlice'
import { toast } from 'react-toastify'
import dayjs from 'dayjs'

type EditTransactionModalProps = {
  transaction: TransactionDTO
}

type ActionType =
  | { type: 'SET_CATEGORY'; payload: string }
  | { type: 'SET_STATUS'; payload: TransactionStatus }
  | { type: 'SET_RECIPIENT'; payload: string }
  | { type: 'SET_TITLE'; payload: string }
  | { type: 'SET_VALUE'; payload: number }
  | { type: 'SET_IS_EXPENSE'; payload: boolean }
  | { type: 'SET_IS_RECURRING'; payload: boolean }
  | { type: 'SET_DATE'; payload: string }
  | { type: 'SET_DESCRIPTION'; payload: string }

const reducer = (state: TransactionDTO, action: ActionType): TransactionDTO => {
  switch (action.type) {
    case 'SET_CATEGORY':
      return { ...state, categoryId: action.payload }
    case 'SET_STATUS':
      return { ...state, status: action.payload }
    case 'SET_RECIPIENT':
      return { ...state, recipient: action.payload }
    case 'SET_TITLE':
      return { ...state, title: action.payload }
    case 'SET_VALUE':
      return { ...state, value: action.payload }
    case 'SET_IS_EXPENSE':
      return { ...state, isExpense: action.payload }
    case 'SET_IS_RECURRING':
      return { ...state, isRecurring: action.payload }
    case 'SET_DATE':
      return { ...state, date: action.payload }
    case 'SET_DESCRIPTION':
      return { ...state, description: action.payload }
    default:
      return state
  }
}

type StatusOption = {
  id: number
  value: TransactionStatus
  name: string
}

const statuses: StatusOption[] = [
  {
    id: 0,
    value: 'FINISHED',
    name: 'Opłacona'
  },
  {
    id: 1,
    value: 'PENDING',
    name: 'Oczekująca'
  }
]

const EditTransactionModal = ({
  open,
  handleOpen,
  handleClose,
  transaction
}: EditTransactionModalProps & ModalProps) => {
  // MANAGE CATEGORIES MODAL STATE
  const [categoryOpen, setCategoryOpen] = useState(false)

  // CATEGORIES MODAL HANDLERS
  const handleCategoryOpen = () => {
    handleClose()
    setCategoryOpen(true)
  }

  const handleCategoryClose = () => {
    if (handleOpen) handleOpen()
    setCategoryOpen(false)
  }

  const [state, dispatch] = useReducer(reducer, transaction)

  const handleCategoryChange = (newCategory: string) => {
    dispatch({ type: 'SET_CATEGORY', payload: newCategory })
  }

  const handleStatusChange = (newStatus: TransactionStatus) => {
    dispatch({ type: 'SET_STATUS', payload: newStatus })
  }

  const handleRecipientChange = (newRecipient: string) => {
    dispatch({ type: 'SET_RECIPIENT', payload: newRecipient })
  }

  const handleTitleChange = (newTitle: string) => {
    dispatch({ type: 'SET_TITLE', payload: newTitle })
  }

  const handleValueChange = (newValue: number) => {
    dispatch({ type: 'SET_VALUE', payload: newValue })
  }

  const handleIsExpenseChange = (newValue: boolean) => {
    dispatch({ type: 'SET_IS_EXPENSE', payload: newValue })
  }

  const handleIsRecurringChange = (newValue: boolean) => {
    dispatch({ type: 'SET_IS_RECURRING', payload: newValue })
  }

  const handleDateChange = (newDate: string) => {
    dispatch({ type: 'SET_DATE', payload: newDate })
  }

  const handleDescriptionChange = (newDescription: string) => {
    dispatch({ type: 'SET_DESCRIPTION', payload: newDescription })
  }

  const [editTransaction] = useEditTransactionMutation()

  const handleConfirm = () => {
    editTransaction({ ...state, date: dayjs(state.date).format('YYYY-MM-DD') })
      .unwrap()
      .then(() => {
        toast.success('Transakcja została zmodyfikowana pomyślnie!', {
          position: 'bottom-right',
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: 'colored'
        })
        handleClose()
      })
      .catch(() => {
        toast.warn('Nie udało się zmodyfikować transakcji.', {
          position: 'bottom-right',
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: 'colored'
        })
      })
  }

  return (
    <>
      {open && (
        <Modal handleClose={handleClose}>
          <ModalHeader
            handleClose={handleClose}
            title={'Edycja transakcji'}
            subtitle={transaction?.title}
          />
          <SelectCategory
            value={state.categoryId}
            handleChange={(e) => handleCategoryChange(e.target.value)}
            handleCategoryOpen={handleCategoryOpen}
            categoryTypes={['TRANSACTION']}
          />
          <Select
            options={statuses.map((s) => {
              let option: Option = { id: s.id, name: s.name }
              return option
            })}
            label="Status"
            placeholder={'Wybierz status'}
            handleSelect={(e) => handleStatusChange(e.target.value as TransactionStatus)}
            value={state.status}
          />
          <Input
            label="Odbiorca"
            value={state.recipient}
            type={'text'}
            placeholder={'Odbiorca ...'}
            handleChange={(e) => handleRecipientChange(e.target.value)}
          />
          <Input
            label="Nazwa"
            value={state.title}
            type={'text'}
            placeholder={'Nazwa ...'}
            handleChange={(e) => handleTitleChange(e.target.value)}
          />
          <Input
            label="Wartość"
            value={state.value}
            type={'text'}
            placeholder={'Wartość ...'}
            handleChange={(e) => handleValueChange(+e.target.value)}
          />
          <Checkbox
            label={'Wydatek'}
            id={'is-expense-checkbox'}
            checked={state.isExpense}
            handleChange={(value: boolean) => handleIsExpenseChange(value)}
          />
          <Checkbox
            label={'Tranakcja cykliczna'}
            id={'is-recurring-checkbox'}
            checked={state.isRecurring}
            handleChange={(value: boolean) => handleIsRecurringChange(value)}
          />
          <SelectDate
            value={dayjs(state.date).format('YYYY-MM-DD')}
            handleChange={(e) => handleDateChange(e.target.value)}
            id="edit-transaction-date-select"
          />
          <TextArea
            label="Opis"
            id="description-text-area"
            value={state.description}
            handleChange={(e) => handleDescriptionChange(e.target.value)}
          />
          <ModalFooter handleClose={handleClose} handleConfirm={handleConfirm} />
        </Modal>
      )}
      <ManageCategoriesModal open={categoryOpen} handleClose={handleCategoryClose} />
    </>
  )
}

export default EditTransactionModal
