// apps/client-react/src/components/text/TextWithDescription.tsx
type TextWithDescriptionProps = {
  text: string
  description: string | undefined
}

const TextWithDescription = ({ text, description }: TextWithDescriptionProps) => {
  return (
    <div>
      <h3 className="font-semibold text-background-700">{text}</h3>
      <span className="text-background-600">{description ? description : '-'}</span>
    </div>
  )
}

export default TextWithDescription

// apps/client-vue/src/components/sections/TextWithDescription.vue
<script setup lang="ts">
type TextWithDescriptionProps = {
  text: string | undefined
  description: string | undefined
}

const props = withDefaults(defineProps<TextWithDescriptionProps>(), {})
</script>

<template>
  <div class="pl-4">
    <h3 class="font-semibold text-background-700">{{ props.text }}</h3>
    <span class="text-background-600">{{ props.description }}</span>
  </div>
</template>
