// apps/client-react/src/layout/SidebarContainer.tsx
import { useState } from 'react';
import SidebarCollapseButton from '../components/sidebar/SidebarCollapseButton.tsx';
import SidebarLeft from '../components/sidebar/SidebarLeft.tsx';
import SidebarRight from '../components/sidebar/SidebarRight.tsx';

type SidebarContainerProps = {
  side: 'left' | 'right';
};

const SidebarContainer = ({ side }: SidebarContainerProps) => {
  const [open, setOpen] = useState(false);

  const classesContainerBase = `h-screen top-0 fixed bg-transparent px-4 py-4 ${
    side === 'left' ? 'left-0' : 'right-0'
  } absolute transition-all duration-300 ease-in-out`;
  const classesContainerOpen = 'w-[12%] min-w-[14rem]';
  const classesContainerClosed = 'w-[4%] min-w-[5rem]';

  const classesSidebarBase =
    'rounded-xl shadow-2xl h-full w-full flex flex-col justify-between py-5 bg-primary-medium overflow-y-auto overflow-x-hidden';
  const classesSidebarClosed = 'px-2';
  const classesSidebarOpen = 'px-5';

  return (
    <div className={`${classesContainerBase} ${open ? classesContainerOpen : classesContainerClosed}`}>
      <div className={`${classesSidebarBase} ${open ? classesSidebarOpen : classesSidebarClosed}`}>
        <SidebarCollapseButton side={side} open={open} setOpen={setOpen} />
        {side === 'left' ? <SidebarLeft open={open} /> : <SidebarRight open={open} />}
      </div>
    </div>
  );
};

export default SidebarContainer;

// apps/client-vue/src/components/sidebar/SidebarContainer.vue
<script setup lang="ts">
defineProps<{
  isOpen: boolean
  toggleFunction: () => void
}>()

const openClasses = 'w-72'
const closedClasses = 'w-10'
</script>

<template>
  <!-- Sidebar wrapper -->
  <div
    :class="`h-full sticky top-0 left-0 transition-all ease-in-out duration-300 flex justify-between ${
      isOpen ? openClasses : closedClasses
    }`"
  >
    <!-- Sidebar tile -->
    <div
      class="bg-background-50 w-full h-full shadow-large rounded-xl px-4 py-4 flex flex-col justify-between"
    >
      <!-- <span v-if="isOpen">Open</span>
      <span v-else>Closed</span> -->

      <!-- <button @click="toggleFunction">Toggle</button> -->
      <slot> </slot>
    </div>
  </div>
</template>
