// apps/client-qwik/src/components/modal/accounts/AddAccountModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, $, useStore } from '@builder.io/qwik'
import { Modal } from '../Modal'
import type { AccountDTO } from 'shared-types'
import { useCategories } from '~/api/categoriesAPI'
import { useAddAccount } from '~/api/accountsAPI'
import { ManageCategoriesModal } from '../categories/ManageCategoriesModal'
import { Plus } from '~/icons'
import { Button } from '~/components/buttons/Button'

type AddAccountModalProps = {
  open: QRL<() => void>
  close: QRL<() => void>
}

export const AddAccountModal = component$(({ close }: AddAccountModalProps) => {
  const categories = useCategories()
  const addAccount = useAddAccount()

  const state = useStore({
    name: '',
    balance: 0,
    selectedCategory: categories.value[0].id,
    isManageCategoriesModalOpen: false
  })

  const handleConfirm = $(async () => {
    const newAccount: Partial<AccountDTO> = {
      name: state.name,
      balance: state.balance,
      category: state.selectedCategory
    }
    await addAccount.submit(newAccount)
    close()
  })

  const handleCancel = $(() => {
    close()
  })

  const handleOpenCategoriesMenu = $(() => {
    state.isManageCategoriesModalOpen = true
  })

  const handleCloseCategoriesMenu = $(() => {
    state.isManageCategoriesModalOpen = false
  })

  return (
    <>
      <Modal title="Nowe konto" handleConfirm={handleConfirm} handleCancel={handleCancel}>
        <div class="flex flex-col gap-1">
          <label for="account-name-input">Nazwa </label>
          <input
            id="account-name-input"
            type="text"
            onInput$={(e) => (state.name = (e.target as HTMLInputElement).value)}
          />
        </div>

        <div class="flex flex-col gap-1">
          <div class="flex flex-row w-full items-center justify-between">
            <label for="account-category-select">Kategoria</label>
            <Button color="neutral" onClick={handleOpenCategoriesMenu}>
              <Plus />
            </Button>
          </div>
          <select
            value={state.selectedCategory}
            onChange$={(e) => (state.selectedCategory = (e.target as HTMLSelectElement).value)}
          >
            {categories.value
              .filter((c) => c.categoryType === 'ACCOUNT')
              .map((c) => (
                <option value={c.id} key={`category-select-option-${c.id}`}>
                  {c.name}
                </option>
              ))}
          </select>
        </div>

        <div class="flex flex-col gap-1">
          <label for="account-balance-input">Stan konta</label>
          <input
            id="account-balance-input"
            type="number"
            onInput$={(e) => (state.balance = +(e.target as HTMLInputElement).value)}
          />
        </div>
      </Modal>

      {state.isManageCategoriesModalOpen && (
        <ManageCategoriesModal close={handleCloseCategoriesMenu} />
      )}
    </>
  )
})

// apps/client-vue/src/components/modal/modals/AddAccountModal.vue
<script setup lang="ts">
import Plus from '@/components/icons/Plus.vue'
import Button from '@/components/buttons/Button.vue'
import Modal from '../Modal.vue'
import { onMounted, ref, watch } from 'vue'
import IconOnlyButton from '@/components/buttons/IconOnlyButton.vue'
import accountsService from '../../../services/accountsService'
import { AccountDTO, CategoryDTO } from '../../../../../../packages/shared-types/types'

type CreateAccountProps = {
  handleCreate: (newAccount: Partial<AccountDTO>) => void
}

const props = withDefaults(defineProps<CreateAccountProps>(), {})

const open = ref(false)
const categories = ref<CategoryDTO[]>([])
const name = ref<string>()
const balance = ref<number>()
const selectedCategory = ref<string>()

const emit = defineEmits(['refetch'])

async function getAccountsCategories() {
  categories.value = await accountsService.getAccountsCategories('123')
}

async function createAccount() {
  let newAccount: Partial<AccountDTO> = {
    name: name.value,
    balance: balance.value,
    category: selectedCategory.value
  }
  props.handleCreate(newAccount)
  handleClose()
}

const handleOpen = () => (open.value = true)
const handleClose = () => (open.value = false)
const handleConfirm = () => {
  createAccount()
}

onMounted(getAccountsCategories)
watch(selectedCategory, (newValue) => {
  console.log(newValue)
})
</script>

<template>
  <Button color="neutral" @click="handleOpen"> <Plus class="text-sm" /> Dodaj konto </Button>
  <Modal
    v-if="open"
    :title="'Nowe konto'"
    :handle-confirm="handleConfirm"
    :handle-cancel="handleClose"
  >
    <div class="flex flex-col gap-4 pt-2 pb-4">
      <div class="flex flex-col">
        <label htmlFor="account-name">Nazwa</label>
        <input type="text" id="account-name" placeholder="Podaj nazwę konta ..." v-model="name" />
      </div>

      <div class="flex flex-col">
        <label htmlFor="account-balance">Stan konta</label>
        <input
          type="number"
          id="account-balance"
          placeholder="Podaj bilans konta ..."
          v-model="balance"
        />
      </div>

      <div class="flex flex-col">
        <div class="flex flex-row justify-between items-center">
          <label htmlFor="accaount-category">Kategoria</label>
          <IconOnlyButton color="neutral" size="small"><Plus /></IconOnlyButton>
        </div>
        <!-- 
        <v-select v-model="selectedCategory" :options="categories" value="id" label="name">
        </v-select> -->
        <select
          name="category"
          id="accaount-category"
          v-model="selectedCategory"
          placeholder="Wybierz ktageorię konta..."
        >
          <option v-for="category in categories" :key="category.id" :value="category.id">
            {{ category.name }}
          </option>
        </select>
      </div>
    </div>
  </Modal>
</template>
