// apps/client-vue/src/components/header/Header.vue
<script>
export default {
  components: {},
  data() {
    return {};
  },
};
</script>

<template>
  <div
    class="w-full h-10 bg-slate-300 flex flex-row justify-between items-center px-5 sm:px-5 md:px-10 lg:px-15 lg:px-20 xl:px-25 2xl:px-25"
  >
    <div class="bg-pink-300">Logo</div>
    <div class="bg-pink-300">
      <a href="#">O projekcie</a>
      <a href="#">Strona główna</a>
      <a href="#">Funkcje</a>
    </div>
    <div class="bg-pink-300 flex flex-row gap-10">
      <button>Tłumaczenie</button>
      <button>Dzień/noc</button>
      <button>Zaloguj się</button>
    </div>
  </div>
</template>

// apps/client-react/src/components/header/Header.tsx
import Logo from '../logo/Logo.tsx';
import NavigationLink from '../links/NavigationLink.tsx';
import NavigationContainer from '../containers/NavigationContainer.tsx';
import IconButton from '../buttons/IconButton.tsx';
import { Globe, Moon } from '../icons/basil/index.ts';
import Button from '../buttons/Button.tsx';

const Header = () => {
  return (
    // TODO: Separate to tailwind class
    <div className="w-full h-10 flex flex-row justify-between items-center px-48 mt-11">
      <div className="flex flex-row justify-start items-center gap-8 w-64">
        <Logo />
      </div>
      <NavigationContainer>
        <NavigationLink text="O projekcie" to="/" />
        <NavigationLink text="Strona główna" to="/" />
        <NavigationLink text="Funkcje" to="/" />
      </NavigationContainer>
      <div className="flex flex-row justify-end items-center gap-8 w-64">
        <IconButton icon={<Globe />} />
        <IconButton icon={<Moon />} />
        <Button text="Zaloguj się" />
      </div>
    </div>
  );
};

export default Header;
