// apps/client-react/src/components/modal/account/DeleteAccountModal.tsx
import Modal from '../Modal'
import { ModalProps } from 'shared-types'
import ModalHeader from '../sections/ModalHeader'
import { useNavigate, useParams } from 'react-router-dom'
import {
  useDeleteAccountMutation,
  useGetAccountQuery
} from '../../../redux/api/slices/accountSlice'
import ModalFooter from '../sections/ModalFooter'
import { toast } from 'react-toastify'

const DeleteAccountModal = ({ open, handleClose }: ModalProps) => {
  const navigate = useNavigate()
  const { id } = useParams()
  const { data: account } = useGetAccountQuery({
    id: id
  })

  const [deleteAccount] = useDeleteAccountMutation()

  const handleConfirm = () => {
    if (id) {
      deleteAccount(id)
        .unwrap()
        .then(() => {
          navigate('/accounts')
          toast.success('Konto zostało usunięte pomyślnie!', {
            position: 'bottom-right',
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: true,
            pauseOnHover: true,
            draggable: true,
            progress: undefined,
            theme: 'colored'
          })
          handleClose()
        })
        .catch(() => {
          toast.warn('Nie udało się usunąć konta.', {
            position: 'bottom-right',
            autoClose: 5000,
            hideProgressBar: false,
            closeOnClick: true,
            pauseOnHover: true,
            draggable: true,
            progress: undefined,
            theme: 'colored'
          })
        })
    } else {
      toast.warn('Nie odnaleziono konta.', {
        position: 'bottom-right',
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        theme: 'colored'
      })
    }
  }

  return (
    <>
      {open && (
        <Modal handleClose={handleClose}>
          <ModalHeader
            handleClose={handleClose}
            title={'Usuwanie konta'}
            subtitle={account?.name}
          />
          <ModalFooter handleClose={handleClose} handleConfirm={handleConfirm} />
        </Modal>
      )}
    </>
  )
}

export default DeleteAccountModal

// apps/client-qwik/src/components/modal/accounts/DeleteAccountModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, $ } from '@builder.io/qwik'
import type { AccountDTO } from 'shared-types'
import { Modal } from '../Modal'
import { useNavigate } from '@builder.io/qwik-city'
import { useDeleteAccount } from '~/api/accountsAPI'

type DeleteAccountModalProps = {
  account: AccountDTO
  open: QRL<() => void>
  close: QRL<() => void>
}

export const DeleteAccountModal = component$(({ account, close }: DeleteAccountModalProps) => {
  const deleteAccount = useDeleteAccount()
  const nav = useNavigate()
  const handleConfirm = $(async () => {
    deleteAccount.submit().then(() => {
      nav('/accounts')
      close()
    })
  })

  const handleCancel = $(() => {
    close()
  })

  return (
    <Modal
      title="Usuwanie konta"
      subtitle={account.name}
      handleConfirm={handleConfirm}
      handleCancel={handleCancel}
    >
      Czy na pewno chcesz usunąć konto {account.name}?
    </Modal>
  )
})
