// apps/client-vue/src/components/modal/sections/ModalHeader.vue
<script setup lang="ts">
import Button from '@/components/buttons/Button.vue'
import Cross from '@/components/icons/Cross.vue'
type ModalHeaderProps = {
  handleClose: () => void
  title: string
  subtitle?: string
}

const props = withDefaults(defineProps<ModalHeaderProps>(), {})
</script>

<template>
  <div class="w-full flex flex-row justify-between items-start">
    <div class="flex flex-col gap-2">
      <h2 class="text-lg font-semibold text-background-700">{{ props.title }}</h2>
      <h3 v-if="props.subtitle" className="text-bs text-background-500">{{ props.subtitle }}</h3>
    </div>
    <Button color="neutral" size="small"><Cross /></Button>
  </div>
</template>

// apps/client-react/src/components/modal/sections/ModalHeader.tsx
import Button from '../../buttons/Button'
import { Cross } from '../../icons'

type ModalHeaderProps = {
  handleClose: () => void
  title: string
  subtitle?: string
}

const ModalHeader = ({ handleClose, title, subtitle }: ModalHeaderProps) => {
  return (
    <div className="w-full flex flex-row justify-between items-start">
      <div className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold text-background-700">{title}</h2>
        {subtitle && <h3 className="text-bs text-background-500">{subtitle}</h3>}
      </div>
      <Button
        variant="icon-only"
        color="neutral"
        size="small"
        IconLeft={Cross}
        onClick={handleClose}
      />
    </div>
  )
}

export default ModalHeader
