// apps/client-vue/src/views/general/LoginPage.vue
<script lang="ts">
import Logo from '@/components/logo/Logo.vue'
import { ref } from 'vue'
// import { useUserStore } from '@stores/UserStore'
// import { router } from '@/main'
// import { login } from '@api/UserAPI'

export default {
  props: [],
  components: {
    Logo
  },
  setup() {
    // USER STORE
    // const userStore = useUserStore()

    // FORM INPUTS
    const email = ref('')
    const password = ref('')
    const alert = ref('')

    async function handleSubmit() {
      try {
        // login(email.value, password.value).then((response: any) => {
        //   if (response.status === 400) {
        //     alert.value = 'Wprowadzono błędne dane'
        //   } else {
        //     console.log(response.data)
        //     userStore.login(response.token)
        //     router.push('/')
        //     console.log(userStore.isLoggedIn)
        //   }
        // if (response.status === 200) {
        //   // Login successful
        //   userStore.login(response.token)
        //   router.push({ path: '/' })
        // } else if (response.status === 400) {
        //   // Bad request, incorrect credentials
        //   alert.value = 'Wprowadzono błędne dane'
        // } else {
        //   // Handle other status codes as needed
        //   alert.value = 'Wystąpił błąd podczas logowania'
        // }
        // })
      } catch (error) {
        console.error(error)
        alert.value = 'Wystąpił błąd podczas logowania'
      }
    }
    return {
      alert,
      email,
      password,
      handleSubmit
    }
  }
}
</script>

<template>
  <div class="flex flex-row w-full h-screen justify-between items-start gap-6 mb-3">
    <div class="flex flex-col w-full h-screen bg-neutral-300">
      <Logo />
    </div>

    <!-- FROM -->
    <div class="flex flex-col w-full h-screen bg-neutral-300 justify-center items-center gap-4">
      <div class="flex flex-col w-60 items-start">
        <h1 class="text-2xl font-slab">Witaj</h1>
        <h1 class="text-2xl font-slab">Ponownie!</h1>
      </div>
      <div class="flex flex-col w-60">
        <label htmlFor="mail-input">Adres e-mail</label>
        <input type="text" id="mail-input" v-model="email" />
      </div>
      <div class="flex flex-col w-60">
        <label htmlFor="mail-input">Hasło</label>
        <input type="password" id="password-input" v-model="password" />
      </div>
      <button class="bg-primary-400 w-60 py-1 rounded-lg" @click="handleSubmit">Zaloguj się</button>

      <span class="text-red-600">{{ alert }}</span>
    </div>
  </div>
</template>

// apps/client-react/src/views/general/LoginPage.tsx
import { useState } from 'react'
import { Envelope } from '../../components/icons'
import { Link, useNavigate } from 'react-router-dom'
import Input from '../../components/inputs/Input'
import { Lock } from '../../components/icons'
import Button from '../../components/buttons/Button'
import { login } from '../../api/auth'

const LoginPage = () => {
  // NAVIGATION
  const navigate = useNavigate()

  // FORM VALUES
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')

  const handleEmailChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newEmail = event.target.value
    setEmail(newEmail)
  }

  const handlePasswordChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newPassword = event.target.value
    setPassword(newPassword)
  }

  const handleLogin = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()

    // const response = await login({ email, password })
    // const data = await response.json()

    // if (response.status === 201) {
    //   console.log(data)
    // } else {
    //   console.log(data.message)
    //   setError(data.message)
    // }

    try {
      const response = await login({ email, password })
      const data = await response.json()

      console.log(response.status)
      console.log(data)

      if (data.token) {
        navigate('/')
      }
    } catch (error: any) {
      setError(error.message)
      console.log()
    }
  }

  return (
    <div className="flex flex-row w-full h-full bg-neutral-200">
      <div className="bg-gradient-to-tr from-primary-800 to-primary-700 w-3/5"></div>

      <div className="bg-white w-2/5 shadow-2xl shadow-primary-900 flex flex-col justify-center items-center px-20">
        <form
          className="flex flex-col justify-center items-start w-full gap-8"
          onSubmit={handleLogin}
        >
          <h1 className="text-transparent leading-7 py-1 text-3xl font-slab font-extrabold bg-clip-text bg-gradient-to-tr from-primary-700 to-primary-600">
            Witaj <br />
            ponownie!
          </h1>

          <div className="flex flex-col justify-center items-start w-full gap-3 pt-4">
            <span className="text-red-600">{error}</span>
            <Input
              label={'Adres e-mail'}
              type={'email'}
              placeholder={'Podaj adres e-mail ...'}
              Icon={Envelope}
              handleChange={handleEmailChange}
            />

            <div className="flex flex-col relative w-full gap-2">
              <Input
                label={'Hasło'}
                type={'password'}
                placeholder={'Podaj hasło ...'}
                Icon={Lock}
                handleChange={handlePasswordChange}
              />
              <div className="flex flex-row w-full justify-between items-center">
                <div className="flex flex-row gap-2">
                  <input type="checkbox" id="remember-me-checkbox" />
                  <label
                    htmlFor="remember-me-checkbox"
                    className="text-sm font-bold text-background-700"
                  >
                    Zapamiętaj
                  </label>
                </div>
                <a href="#" className="text-sm font-bold text-primary-600">
                  Nie pamietasz hasła?
                </a>
              </div>
            </div>
          </div>

          <div className="flex flex-col w-full justify-center items-center gap-4 mt-4">
            <Button type="submit" text="Zaloguj się" size="large" fullWidth />
            <div className="flex flex-row justify-center items-center gap-2">
              <span className="text-sm font-bold text-background-700">Nie masz konta?</span>
              <Link to="/register" className="text-sm font-bold text-primary-600">
                Zarejestruj się
              </Link>
            </div>
          </div>
        </form>
      </div>
    </div>
  )
}

export default LoginPage
