// apps/client-vue/src/components/charts/SummaryDoughnut.vue
<script setup lang="ts">
import { Chart as ChartJS, ArcElement, Tooltip, Legend } from 'chart.js'
import TransactionDTO from 'shared-types/types/dto/TransactionDTO'
import { computed } from 'vue'
import { Doughnut } from 'vue-chartjs'

ChartJS.register(ArcElement, Tooltip, Legend)

// PROPS
type SummaryDonutChartProps = {
  transactions: TransactionDTO[]
}

const props = withDefaults(defineProps<SummaryDonutChartProps>(), {})

// STATE
const incomesSum = computed(() =>
  props.transactions.filter((t) => !t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
)

const expensesSum = computed(() =>
  props.transactions.filter((t) => t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
)

const data = computed(() => ({
  labels: ['Dochody', 'Wydatki'],
  datasets: [
    {
      data: [incomesSum.value, expensesSum.value],
      label: 'Suma',
      backgroundColor: ['#8DBE88', '#E68080'],
      circumference: 180,
      rotation: 270
    }
  ]
}))

const options = {
  plugins: {
    legend: {
      display: false
    }
  }
}

// OPTIONS
</script>

<template>
  <div class="flex flex-row justify-center items-center h-56">
    <Doughnut :data="data" :options="options" />
  </div>
</template>

// apps/client-qwik/src/components/charts/accounts/SummaryDoughnut.tsx
import { component$, useSignal } from '@builder.io/qwik'
import { DoughnutChart } from '../DoughnutChart'
import type { TransactionDTO } from 'shared-types'
import type { Dataset } from 'shared-types/types/components/charts/Doughnut'

type SummaryDoughnutProps = {
  transactions: TransactionDTO[]
}

export const SummaryDoughnut = component$(({ transactions }: SummaryDoughnutProps) => {
  const incomesSum = useSignal(
    transactions.filter((t) => !t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
  )
  const expensesSum = useSignal(
    transactions.filter((t) => t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
  )

  const labels = ['Dochody', 'Wydatki']
  const datasets = useSignal<Dataset[]>([
    {
      label: 'Suma',
      data: [incomesSum.value, expensesSum.value],
      backgroundColor: ['#8DBE88', '#E68080'],
      circumference: 180,
      rotation: 270
    }
  ])

  return (
    <div class="flex flex-row justify-center items-center h-56">
      <DoughnutChart id="overview-doughnut-chart" labels={labels} datasets={datasets.value} />
    </div>
  )
})
