// apps/client-react/src/views/accounts/AccountPage.tsx
import { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { setPageHeaderState, setPageName } from '../../redux/slices/pageHeaderSlice'
import { useNavigate, useParams } from 'react-router-dom'
import ContentContainer from '../../components/containers/ContentContainer'
import { useGetAccountQuery } from '../../redux/api/slices/accountSlice'
import { RootState } from '../../redux/store'
import { useGetUsersCategoriesQuery } from '../../redux/api/slices/categorySlice'
import TextWithDescription from '../../components/text/TextWithDescription'
import { CategoryDTO, TransactionDTO } from 'shared-types'
import SelectGraph from '../../components/inputs/SelectGraph'
import SelectDate from '../../components/inputs/SelectDate'
import Checkbox from '../../components/inputs/Checkbox'
import Button from '../../components/buttons/Button'
import Searchbar from '../../components/inputs/Searchbar'
import { handleValueChange } from '../../utils'
import { ArrowLeft, Filter, Plus } from '../../components/icons'
import TableHeadCell from '../../components/table/TableHeadCell'
import { useGetUsersTransactionsQuery } from '../../redux/api/slices/transactionSlice'
import ManageTransactionModal from '../../components/modal/ManageTransactionModal'
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip as ChartTooltip,
  CategoryScale,
  LinearScale,
  Legend,
  BarElement
} from 'chart.js'
import EditAccountButton from '../../components/page-header/buttons/EditAccountButton'
import DeleteAccountButton from '../../components/page-header/buttons/DeleteAccountButton'
import DonutChart from '../../components/graph/DonutChart'
import Radio from '../../components/inputs/Radio'
import Tooltip from '../../components/tooltip/Tooltip'
import { BarChart } from '../../components/graph/BarChart'
import dayjs from 'dayjs'
import TransactionsTableRow from '../../components/table/TransactionsTableRow'
import FilterTransactionsMenu from '../../components/menu/FilterTransactionsMenu'
import { formatCurrency } from 'shared-utils/utils/formatCurrency'

const AccountPage = () => {
  ChartJS.register(ArcElement, ChartTooltip, Legend, CategoryScale, LinearScale, BarElement)

  const dispatch = useDispatch()
  const navigate = useNavigate()
  const { id } = useParams()
  const currentUser = useSelector((state: RootState) => state.currentUser.currentUser)
  const [accountCategory, setAccountCategory] = useState<CategoryDTO | null>(null)
  const [transactionCategories, setTransactionCategories] = useState<CategoryDTO[]>([])

  // ACCOUNT
  const { data: account, isSuccess: isAccountSuccess } = useGetAccountQuery({
    id: id
  })

  // CATEGORIES
  const { data: categories, isSuccess: isCategoriesSuccess } = useGetUsersCategoriesQuery({
    id: currentUser?.id
  })

  // TRANSACTIONS
  const { data: transactions } = useGetUsersTransactionsQuery({
    id: currentUser?.id
  })

  const [accountTransactions, setAccountTransactions] = useState<TransactionDTO[]>([])
  const [filteredTransactions, setFilteredTransactions] = useState<TransactionDTO[]>([])
  const [visibleTransactions, setVisibleTransactions] = useState<TransactionDTO[]>([])

  const [incomesSum, setIncomesSum] = useState(
    accountTransactions.filter((t) => !t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
  )
  const [expensesSum, setExpensesSum] = useState(
    accountTransactions.filter((t) => t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
  )

  useEffect(() => {
    if (transactions) {
      let accountTransactions = transactions?.filter((t) => t.accountId === id)
      let ids = accountTransactions.map((t) => t.categoryId)
      let filteredCategories = categories?.filter((c) => ids.includes(c.id))
      setTransactionCategories(filteredCategories || [])
      setAccountTransactions(accountTransactions)
      setVisibleTransactions(accountTransactions)
      setIncomesSum(
        accountTransactions.filter((t) => !t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
      )
      setExpensesSum(
        accountTransactions.filter((t) => t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
      )
    }
  }, [transactions])

  useEffect(() => {
    dispatch(
      setPageHeaderState({
        pageName: 'Szczegóły konta',
        isMonthPickerVisible: false,
        isSideButtonVisible: true,
        buttonType: 'EDIT_ACCOUNT'
      })
    )
  }, [])

  useEffect(() => {
    if (account && categories) {
      dispatch(setPageName(account.name))
      let category = categories.find((c) => c.id === account.category)
      if (category) setAccountCategory(category)
    }
  }, [account, isAccountSuccess, isCategoriesSuccess])

  // SELECTED GRAPH TYPE STATE
  const [selectedGraphType, setSelectedGraphType] = useState(0)

  // SELECTED DATE STATE
  const [startDate, setStartDate] = useState<string>(dayjs().format('YYYY-MM-DD'))
  const [endDate, setEndDate] = useState<string>(dayjs().add(6, 'month').format('YYYY-MM-DD'))

  // SEARCHBAR STATE
  const [search, setSearch] = useState<string | undefined>(undefined)

  // TRANSACTION MODAL STATE
  const [transactionModalOpen, setTransactionModalOpen] = useState(false)

  // GRAPH SETTINGS
  const [transactionsType, setTransactionsType] = useState<'incomes' | 'expenses' | 'both'>(
    'incomes'
  )
  const [dataType, setDataType] = useState<'sum' | 'count'>('sum')

  const handleTransactionTypeSelected = (e: React.ChangeEvent<HTMLInputElement>) => {
    let value = e.target.value
    if (value === 'incomes' || value === 'expenses' || value === 'both') setTransactionsType(value)
  }

  const handleDataTypeSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    let value = e.target.value
    if (value === 'sum' || value === 'count') setDataType(value)
  }

  useEffect(() => {
    console.log(selectedGraphType)
  }, [selectedGraphType])

  // FILTERING MENU
  const [filterMenuOpen, setFilterMenuOpen] = useState(true)

  // SEARCHBAR

  function searchTransactions(
    transactions: TransactionDTO[],
    searchString: string
  ): TransactionDTO[] {
    const searchTerm = searchString.trim().toLowerCase()

    return transactions.filter((transaction) => {
      const { title, recipient } = transaction

      const titleMatch = title.toLowerCase().includes(searchTerm)
      const recipientMatch = recipient.toLowerCase().includes(searchTerm)

      return titleMatch || recipientMatch
    })
  }

  useEffect(() => {
    if (search) {
      setVisibleTransactions(searchTransactions(filteredTransactions, search))
    } else {
      setVisibleTransactions(filteredTransactions)
    }
  }, [search, filteredTransactions])

  return (
    <div>
      {isAccountSuccess && isCategoriesSuccess && (
        <div className="flex flex-col justify-start gap-6">
          <div className="flex flex-row justify-between items-end w-full pt-6">
            <div className="flex flex-row gap-4 items-center">
              <Tooltip text="Powrót" side="bottom">
                <Button
                  // variant="icon-only"
                  color="neutral"
                  fullWidth={false}
                  text="Powrót"
                  IconLeft={ArrowLeft}
                  size="small"
                  onClick={() => navigate('/accounts')}
                />
              </Tooltip>
              <h1 className="text-lg text-background-800 font-semibold">{account?.name}</h1>
            </div>

            <div className="flex flex-row gap-4">
              <DeleteAccountButton />
              <EditAccountButton />
            </div>
          </div>
          <div className="flex flex-row justify-between gap-4">
            <div className="flex flex-col w-1/2 gap-3">
              <h2 className="text-md font-semibold text-background-700">Informacje ogólne</h2>
              <div className="flex flex-col gap-4 pl-4">
                <TextWithDescription text="Nazwa" description={account.name} />
                <TextWithDescription text="Rodzaj konta" description={accountCategory?.name} />
                <TextWithDescription
                  text="Bilans"
                  description={formatCurrency(incomesSum - expensesSum)}
                />
              </div>
            </div>

            <div className="flex flex-col w-1/2">
              <h2 className="text-md font-semibold text-background-700">Podsumowanie liczbowe</h2>
              <DonutChart transactionType={transactionsType} dataType={dataType} half />
              <div className="w-full flex flex-row justify-center items-center gap-4">
                <div className="flex flex-col gap-1 w-48">
                  <span className="text-sm text-background-600">Dochody</span>
                  <div className="flex flex-row gap-2">
                    <div className="w-4 h-4 rounded-[4px] bg-[#8dbe88]"></div>
                    <span className="text-xs font-bold text-background-600">
                      {formatCurrency(incomesSum)}
                    </span>
                  </div>
                </div>

                <div className="flex flex-col gap-1 w-48">
                  <span className="text-sm text-background-600">Wydatki</span>
                  <div className="flex flex-row gap-2">
                    <div className="w-4 h-4 rounded-[4px] bg-[#e68080]"></div>
                    <span className="text-xs font-bold text-background-600">
                      {formatCurrency(expensesSum)}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="flex flex-row w-full justify-between items-start">
            <div className="flex flex-col justify-between items-start w-1/2 gap-4">
              <h2 className="text-md font-semibold text-background-700">Podsumowanie liczbowe</h2>
              <div className="flex flex-col gap-2 pl-4">
                <h3 className="text-sm font-bold text-background-600">Rodzaj transakcji</h3>
                <div className="flex flex-row gap-6 pl-4">
                  <Radio
                    value={'incomes'}
                    name={'transactionType'}
                    label={'Dochody'}
                    id={'incomes-radio-button'}
                    handleChange={handleTransactionTypeSelected}
                    checked={transactionsType === 'incomes'}
                  />
                  <Radio
                    value={'expenses'}
                    name={'transactionType'}
                    label={'Wydatki'}
                    id={'expenses-radio-button'}
                    handleChange={handleTransactionTypeSelected}
                    checked={transactionsType === 'expenses'}
                  />
                  <Radio
                    value={'both'}
                    name={'transactionType'}
                    label={'Wszystkie transakcje'}
                    id={'both-radio-button'}
                    handleChange={handleTransactionTypeSelected}
                    checked={transactionsType === 'both'}
                  />
                </div>
              </div>

              <div className="flex flex-col gap-2 pl-4">
                <h3 className="text-sm font-bold text-background-600">Rodzaj danych</h3>
                <div className="flex flex-row gap-6 pl-4">
                  <Radio
                    value={'sum'}
                    name={'dataType'}
                    label={'Suma transakcji'}
                    id={'data-type-sum-radio-button'}
                    checked={dataType === 'sum'}
                    handleChange={handleDataTypeSelect}
                  />
                  <Radio
                    value={'count'}
                    name={'dataType'}
                    label={'Liczba transakcji'}
                    id={'data-type-count-radio-button'}
                    checked={dataType === 'count'}
                    handleChange={handleDataTypeSelect}
                  />
                </div>
              </div>

              <div className="flex flex-col gap-2 pl-4">
                <h3 className="text-sm font-bold text-background-600">Przedział czasowy</h3>
                <div className="flex flex-row justify-between items-center w-full gap-4 pl-4">
                  <SelectDate
                    value={startDate}
                    handleChange={(e) => handleValueChange(e, setStartDate)}
                    id="select-graph-start-date"
                  />
                  <SelectDate
                    value={endDate}
                    handleChange={(e) => handleValueChange(e, setEndDate)}
                    id="select-graph-end-date"
                  />
                </div>
              </div>

              <div className="flex flex-col gap-2 pl-4">
                <h3 className="text-sm font-bold text-background-600">Rodzaj wykresu</h3>
                <SelectGraph
                  value={selectedGraphType}
                  handleChange={(e) => handleValueChange(e, setSelectedGraphType)}
                  className="ml-4"
                />
              </div>
            </div>

            <div className="flex flex-col justify-between items-start w-1/2">
              <h2 className="text-md font-semibold text-background-700">Wykres</h2>
              <div className="w-[80%] flex flex-row justify-center">
                {selectedGraphType == 0 && (
                  <BarChart
                    transactionType={transactionsType}
                    dataType={dataType}
                    startDate={startDate}
                    endDate={endDate}
                  />
                )}

                {selectedGraphType == 1 && (
                  <DonutChart transactionType={transactionsType} dataType={dataType} />
                )}
              </div>
            </div>
          </div>

          <div className="flex flex-col w-full gap-3">
            <h2 className="text-md font-semibold text-background-700">Lista transakcji</h2>
            <div className="flex flex-row gap-6">
              <FilterTransactionsMenu
                open={filterMenuOpen}
                transactions={accountTransactions}
                categories={transactionCategories}
                setVisibleTransactions={setFilteredTransactions}
              />
              <div className="flex flex-col w-full gap-4">
                <div className="flex flex-row items-center w-full">
                  <div className="flex flex-row items-center w-full gap-6">
                    <div>
                      <Button
                        text="Filtruj"
                        IconLeft={Filter}
                        size="small"
                        iconClassName="text-md"
                        onClick={() => setFilterMenuOpen(!filterMenuOpen)}
                      />
                    </div>
                    <div>
                      <Checkbox
                        label="Pokaż szczegółowe dane"
                        id="details-checkbox"
                        checked={false}
                        handleChange={() => {}}
                      />
                    </div>
                  </div>
                  <div className="w-52">
                    <Button
                      text="Dodaj transakcję"
                      onClick={() => setTransactionModalOpen(true)}
                      IconLeft={Plus}
                      size="small"
                      className="w-36"
                    />
                  </div>
                </div>
                <div>
                  <Searchbar value={search} handleChange={(e) => handleValueChange(e, setSearch)} />
                </div>
                <div className="h-[400px] overflow-y-auto">
                  <table className="w-full border-collapse">
                    <thead className="sticky top-0 bg-background-50">
                      <tr className="border-b-2 border-background-200 text-sm font-light text-background-600">
                        <TableHeadCell label={'Status'} />
                        <TableHeadCell label={'Nazwa'} />
                        <TableHeadCell label={'Data'} align="left" />
                        <TableHeadCell label={'Odbiorca'} align="left" />
                        <TableHeadCell label={'Opis'} align="left" />
                        <TableHeadCell label={'Kategoria'} align="left" />
                        <TableHeadCell label={'Kwota'} align="left" />
                        <TableHeadCell label={'Akcja'} />
                      </tr>
                    </thead>

                    <tbody className="h-[200px] overflow-y-auto">
                      {visibleTransactions &&
                        visibleTransactions.map((t) => (
                          <TransactionsTableRow transaction={t} categories={categories} />
                        ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
      <ManageTransactionModal
        id={id}
        open={transactionModalOpen}
        handleOpen={() => setTransactionModalOpen(true)}
        handleClose={() => setTransactionModalOpen(false)}
      />
    </div>
  )
}

export default AccountPage

// apps/client-vue/src/views/accounts/AccountPage.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { AccountDTO, CategoryDTO, TransactionDTO } from '../../../../../packages/shared-types/types'
import api from '../../services/api.ts'
import accountsService from '../../services/accountsService.ts'
import { useRoute } from 'vue-router'
import ArrowLeft from '@/components/icons/ArrowLeft.vue'
import { router } from '@/main'
import Button from '../../components/buttons/Button.vue'
import Trash from '@icons/Trash.vue'
import Edit from '@icons/Edit.vue'
import Filter from '@icons/Filter.vue'
import Plus from '@/components/icons/Plus.vue'
import DeleteAccountModal from '@/components/modal/account/DeleteAccountModal.vue'
import EditAccountModal from '@/components/modal/account/EditAccountModal.vue'
import AddTransactionModal from '@/components/modal/transaction/AddTransactionModal.vue'
import TransactionTableRow from '@/components/table/TransactionTableRow.vue'
import FilterTransactionsMenu from '@/components/menu/FilterTransactionsMenu.vue'
import SummaryDoughnut from '@/components/charts/SummaryDoughnut.vue'
import utils from 'shared-utils'
import Donut from '@/components/charts/Donut.vue'
import dayjs from 'dayjs'
import Bar from '@/components/charts/Bar.vue'
// import ButtonOptions from '@/components/buttons/ButtonOptions'
import TextWithDescription from '@/components/sections/TextWithDescription.vue'

// STATE
const transactions = ref<TransactionDTO[]>([])
const filteredTransactions = ref<TransactionDTO[]>([])
const visibleTransactions = ref<TransactionDTO[]>([])

const categories = ref<CategoryDTO[]>([])
const account = ref<AccountDTO>()
const id = ref()
const searchInput = ref<string>('')

const incomesSum = computed(() =>
  transactions.value.filter((t) => !t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
)

const expensesSum = computed(() =>
  transactions.value.filter((t) => t.isExpense).reduce((prev, curr) => prev + curr.value, 0)
)

// API
async function getTransactions(accountId: string) {
  transactions.value = await accountsService.getAccountsTransactions('123', accountId)
}

async function getCategories(id: string) {
  categories.value = await api.categories.getUsersCategories(id)
}

async function getAccountById(id: string) {
  api.accounts.getAccountById(id).then((response) => (account.value = response))
}

// HOOKS
const route = useRoute()
onMounted(() => {
  id.value = route.params.id
  getTransactions(id.value).then(() => {
    visibleTransactions.value = transactions.value
    filteredTransactions.value = transactions.value
  })
  getAccountById(id.value)
  getCategories('123')
})

// CHART OPTIONS
const selectedTransacitonType = ref<'INCOMES' | 'EXPENSES' | 'BOTH'>('INCOMES')
const selectedDataType = ref<'SUM' | 'COUNT'>('SUM')
const startDate = ref<string>(dayjs().format('YYYY-MM-DD').toString())
const endDate = ref<string>(dayjs().add(6, 'month').format('YYYY-MM-DD').toString())
const selectedChartType = ref<'DOUGHNUT' | 'BAR'>('DOUGHNUT')

// MODAL
const isEditAccountModalOpen = ref(false)
const isDeleteAccountModalOpen = ref(false)
const isAddTransactionModalOpen = ref(false)

// HANDLERS

const handleReturn = () => {
  router.push('/accounts')
}

const getCategoryName = (id: string) => categories.value.find((c) => c.id === id)?.name

function searchTransactions(
  transactions: TransactionDTO[],
  searchString: string
): TransactionDTO[] {
  const searchTerm = searchString.trim().toLowerCase()

  return transactions.filter((transaction) => {
    const { title, recipient } = transaction

    const titleMatch = title.toLowerCase().includes(searchTerm)
    const recipientMatch = recipient.toLowerCase().includes(searchTerm)

    return titleMatch || recipientMatch
  })
}

function handleSearch() {
  let transactions = searchTransactions(filteredTransactions.value, searchInput.value)
  visibleTransactions.value = transactions
}

// DELETE
function openDeleteAccountModal() {
  isDeleteAccountModalOpen.value = true
}

function closeDeleteAccountModal() {
  isDeleteAccountModalOpen.value = false
}

// EDIT
function openEditAccountModal() {
  isEditAccountModalOpen.value = true
}

function closeEditAccountModal() {
  isEditAccountModalOpen.value = false
}

// NEW TRANSACTION
function openAddTransactionModal() {
  isAddTransactionModalOpen.value = true
}

function closeAddTransactionModal() {
  isAddTransactionModalOpen.value = false
}

function handleRefetch() {
  getAccountById(id.value)
}

function handleRefetchTransactions() {
  getTransactions(id.value)
}

function setFilteredTransactions(transactions: TransactionDTO[]) {
  filteredTransactions.value = transactions
}

function setVisibleTransactions(transactions: TransactionDTO[]) {
  visibleTransactions.value = transactions
}

watch([searchInput, filteredTransactions], () => {
  if (searchInput.value) {
    handleSearch()
  } else {
    setVisibleTransactions(filteredTransactions.value)
  }
})
</script>

<template>
  <div class="content-container gap-8">
    <!-- PAGE HEADER -->
    <div class="w-full flex flex-row justify-between items-center">
      <div class="flex flex-row gap-4 items-center">
        <Button @click="handleReturn" color="neutral" class="px-1 h-6">
          <ArrowLeft class="text-base" /> Powrót
        </Button>
        <!-- <ButtonOptions /> -->
        <h1 class="text-lg text-background-800 font-semibold">{{ account?.name }}</h1>
      </div>
      <div class="flex flex-row gap-4">
        <Button color="neutral" @click="openDeleteAccountModal"
          ><Trash class="text-sm" /> Usuń konto</Button
        >
        <Button color="primary" @click="openEditAccountModal"
          ><Edit class="text-sm" /> Edytuj konto</Button
        >
      </div>
    </div>

    <!-- GENERAL INFO + OVERVIEW STATISTICS SECTION -->
    <div class="flex flex-row justify-between gap-4">
      <div class="flex flex-col w-1/2 gap-3">
        <h2 class="text-md font-semibold text-background-700">Informacje ogólne</h2>

        <TextWithDescription text="Nazwa konta" :description="account?.name" />
        <TextWithDescription text="Kategoria konta" :description="account?.category" />
        <TextWithDescription text="Bilans" :description="`${account?.balance} zł`" />
      </div>

      <div class="flex flex-col w-1/2 gap-2 justify-between">
        <h2 class="text-md font-semibold text-background-700">Podsumowanie liczbowe</h2>

        <SummaryDoughnut :transactions="transactions" />

        <div class="w-full flex flex-row justify-center items-center gap-4">
          <div class="flex flex-col gap-1 w-48">
            <span class="text-sm text-background-600">Dochody</span>
            <div class="flex flex-row gap-2">
              <div class="w-4 h-4 rounded-[4px] bg-[#8dbe88]"></div>
              <span class="text-xs font-bold text-background-600">
                {{ utils.formatCurrency(incomesSum) }}
              </span>
            </div>
          </div>

          <div class="flex flex-col gap-1 w-48">
            <span class="text-sm text-background-600">Wydatki</span>
            <div class="flex flex-row gap-2">
              <div class="w-4 h-4 rounded-[4px] bg-[#e68080]"></div>
              <span class="text-xs font-bold text-background-600">
                {{ utils.formatCurrency(expensesSum) }}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- TRANSACTIONS CHART SECTION -->
    <div class="flex flex-row justify-between gap-4">
      <div class="flex flex-col w-1/2 gap-3">
        <h2 class="text-md font-semibold text-background-700">Opcje wykresu</h2>

        <div class="flex flex-col pl-4 gap-1">
          <h3 class="font-semibold text-background-700">Rodzaj transakcji</h3>
          <div class="flex flex-row gap-4">
            <label class="text-sm text-background-600 w-20">
              <input
                type="radio"
                name="transaction-type"
                value="INCOMES"
                v-model="selectedTransacitonType"
              />
              Dochody
            </label>
            <label class="text-sm text-background-600 w-20">
              <input
                type="radio"
                name="transaction-type"
                value="EXPENSES"
                v-model="selectedTransacitonType"
              />
              Wydatki
            </label>
            <label class="text-sm text-background-600 w-20">
              <input
                type="radio"
                name="transaction-type"
                value="BOTH"
                v-model="selectedTransacitonType"
              />
              Wszystkie
            </label>
          </div>
        </div>

        <div class="flex flex-col pl-4 gap-1">
          <h3 class="font-semibold text-background-700">Rodzaj danych</h3>
          <div class="flex flex-row gap-4">
            <label class="text-sm text-background-600 w-20">
              <input type="radio" name="data-type" value="SUM" v-model="selectedDataType" /> Suma
            </label>
            <label class="text-sm text-background-600 w-20">
              <input type="radio" name="data-type" value="COUNT" v-model="selectedDataType" />
              Liczba
            </label>
          </div>
        </div>

        <div class="flex flex-col pl-4 gap-1">
          <h3 class="font-semibold text-background-700">Przedział czasowy</h3>
          <div class="flex flex-row gap-4 w-2/3">
            <div class="flex flex-col w-1/2">
              <label class="text-sm text-background-600"> Początek </label>
              <input type="date" name="date-start" class="w-full" v-model="startDate" />
            </div>
            <div class="flex flex-col w-1/2">
              <label class="text-sm text-background-600"> Koniec </label>
              <input type="date" name="date-end" class="w-full" v-model="endDate" />
            </div>
          </div>
        </div>

        <div class="flex flex-col pl-4 gap-1">
          <h3 class="font-semibold text-background-700">Rodzaj wykresu</h3>
          <div class="flex flex-row gap-4 w-2/3">
            <select
              name="chart-type"
              id="chart-type-select"
              class="w-full"
              v-model="selectedChartType"
            >
              <option value="DOUGHNUT">Wykres kołowy</option>
              <option value="BAR">Wykres słupkowy</option>
            </select>
          </div>
        </div>
      </div>
      <div class="flex flex-col w-1/2 gap-3">
        <h2 class="text-md font-semibold text-background-700">Wykres podsumowujący</h2>
        <Donut
          v-if="selectedChartType === 'DOUGHNUT'"
          :transactions="transactions"
          :categories="categories"
          :transaction-type="selectedTransacitonType"
          :data-type="selectedDataType"
          :start-date="startDate"
          :end-date="endDate"
        />
        <Bar
          v-if="selectedChartType === 'BAR'"
          :transactions="transactions"
          :transaction-type="selectedTransacitonType"
          :data-type="selectedDataType"
          :start-date="startDate"
          :end-date="endDate"
        />
      </div>
    </div>

    <!-- TRANSACTIONS TABLE SECTION -->
    <div class="flex flex-col gap-4">
      <h3 class="font-semibold text-background-700">Lista transakcji</h3>
      <div class="w-full h-full flex flex-row justify-between">
        <div>
          <FilterTransactionsMenu
            :open="true"
            :transactions="transactions"
            :categories="categories"
            :set-visible-transactions="setFilteredTransactions"
          />
        </div>
        <div class="w-full">
          <div class="flex flex-row justify-between items-center">
            <div class="flex flex-row items-center gap-4">
              <Button><Filter class="text-base" /> <span>Filtruj</span></Button>
              <label> <input type="checkbox" /> Pokaż szczegółowe dane </label>
            </div>
            <div>
              <Button @click="openAddTransactionModal"
                ><Plus class="text-base" /> <span>Dodaj transakcje</span></Button
              >
            </div>
          </div>
          <input
            type="text"
            class="w-full"
            placeholder="Wyszukaj transakcję ..."
            v-model="searchInput"
          />
          <table>
            <thead>
              <th>Status</th>
              <th>Tytuł</th>
              <th>Data</th>
              <th>Odbiorca</th>
              <th>Opis</th>
              <th>Kategoria</th>
              <th>Kwota</th>
              <th>Akcja</th>
            </thead>

            <tbody>
              <TransactionTableRow
                v-for="t in visibleTransactions"
                :refetch="handleRefetchTransactions"
                :t="t"
                :category-name="getCategoryName(t.categoryId) || ''"
              />
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <DeleteAccountModal
      :account="account"
      :is-open="isDeleteAccountModalOpen"
      :open="openDeleteAccountModal"
      :close="closeDeleteAccountModal"
    />

    <EditAccountModal
      :account="account"
      :is-open="isEditAccountModalOpen"
      :open="openEditAccountModal"
      :close="closeEditAccountModal"
      :refetch="handleRefetch"
    />

    <AddTransactionModal
      :account="account"
      :is-open="isAddTransactionModalOpen"
      :open="openAddTransactionModal"
      :close="closeAddTransactionModal"
      :refetch="handleRefetchTransactions"
    />
  </div>
</template>
