// apps/client-qwik/src/components/modal/categories/DeleteCategoryModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, $ } from '@builder.io/qwik'
import type { CategoryDTO, CategoryType } from 'shared-types'
import { Modal } from '../Modal'
import { useDeleteCategory } from '~/api/categoriesAPI'

const dataTypes: Record<CategoryType, string> = {
  ACCOUNT: 'konta',
  TRANSACTION: 'transakcje',
  GOAL: 'cele'
}

type DeleteCategoryModalProps = {
  category: CategoryDTO
  open: QRL<() => void>
  close: QRL<() => void>
}

export const DeleteCategoryModal = component$(({ category, close }: DeleteCategoryModalProps) => {
  const deleteCategory = useDeleteCategory()
  const handleConfirm = $(async () => {
    deleteCategory.submit({ id: category.id })
    close()
  })

  const handleCancel = $(() => {
    close()
  })

  return (
    <Modal
      title="Usuwanie transakcji"
      subtitle={category.name}
      handleConfirm={handleConfirm}
      handleCancel={handleCancel}
    >
      <span>Czy na pewno chcesz usunąć categorię {category.name}?</span>
      <span>
        Wszystkie powiązane z nią {dataTypes[category.categoryType as CategoryType]} zostaną
        usunięte!
      </span>
    </Modal>
  )
})

// apps/client-vue/src/components/modal/category/DeleteCategoryModal.vue
<script setup lang="ts">
import api from '@/services/api'
import Modal from '../Modal.vue'
import { CategoryDTO, CategoryType } from 'shared-types'

// PROPS
type DeleteAccountModalProps = {
  category: CategoryDTO | undefined
}

const dataTypes: Record<CategoryType, string> = {
  ACCOUNT: 'konta',
  TRANSACTION: 'transakcje',
  GOAL: 'cele'
}

type ModalProps = {
  isOpen: boolean
  open: () => void
  close: () => void
  refetch?: () => void
}

const props = withDefaults(defineProps<DeleteAccountModalProps & ModalProps>(), {})

// API
async function deleteCategory() {
  if (props.category)
    await api.categories.deleteCategory(props.category.id).then(() => {
      if (props.refetch) props.refetch()
    })
}

// HANDLERS
async function handleConfirm() {
  deleteCategory()
  props.close()
}

function handleCancel() {
  props.close()
}
</script>

<template>
  <Modal
    v-if="isOpen"
    title="Usuwanie kategorii"
    :subtitle="category?.name"
    :handle-confirm="handleConfirm"
    :handle-cancel="handleCancel"
  >
    <span
      >Czy na pewno chcesz usunąć kategorię <b>{{ category?.name }}</b
      >?</span
    >
    <span
      >Wszystkie powiązane z nią {{ dataTypes[category?.categoryType as CategoryType] }} zostaną
      usunięte!</span
    >
  </Modal>
</template>
