// apps/client-react/src/components/modal/category/DeleteCategoryModal.tsx
import { CategoryDTO, CategoryType, ModalProps } from 'shared-types'
import Modal from '../Modal'
import ModalHeader from '../sections/ModalHeader'
import ModalFooter from '../sections/ModalFooter'
import { useDeleteCategoryMutation } from '../../../redux/api/slices/categorySlice'
import { toast, ToastContainer } from 'react-toastify'

type DeleteCategoryModalProps = {
  category: CategoryDTO
}

const connectedDataType: Record<CategoryType, string> = {
  ACCOUNT: 'kont',
  TRANSACTION: 'transakcji',
  GOAL: 'celów'
}

const DeleteCategoryModal = ({
  open,
  handleClose,
  category
}: DeleteCategoryModalProps & ModalProps) => {
  const [deleteCategory] = useDeleteCategoryMutation()

  const handleConfirm = () => {
    deleteCategory(category.id)
      .unwrap()
      .then(() => {
        toast.success('Kategoria została usunięta pomyślnie!', {
          position: 'bottom-right',
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: 'colored'
        })
        handleClose()
      })
      .catch(() => {
        toast.warn('Nie udało się usunąć kategorii.', {
          position: 'bottom-right',
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
          theme: 'colored'
        })
      })
  }

  return (
    <>
      {open && (
        <Modal handleClose={handleClose}>
          <ModalHeader
            handleClose={handleClose}
            title={'Usuwanie kategorii'}
            subtitle={category.name}
          />
          <div>
            Uwaga! Usunięcie kategorii <b>{category.name}</b> spowoduje usunięcie wszystkich
            powiązanych {connectedDataType[category.categoryType]}!
          </div>
          <ModalFooter handleClose={handleClose} handleConfirm={handleConfirm} />
        </Modal>
      )}
      <ToastContainer />
    </>
  )
}

export default DeleteCategoryModal

// apps/client-qwik/src/components/modal/categories/DeleteCategoryModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, $ } from '@builder.io/qwik'
import type { CategoryDTO, CategoryType } from 'shared-types'
import { Modal } from '../Modal'
import { useDeleteCategory } from '~/api/categoriesAPI'

const dataTypes: Record<CategoryType, string> = {
  ACCOUNT: 'konta',
  TRANSACTION: 'transakcje',
  GOAL: 'cele'
}

type DeleteCategoryModalProps = {
  category: CategoryDTO
  open: QRL<() => void>
  close: QRL<() => void>
}

export const DeleteCategoryModal = component$(({ category, close }: DeleteCategoryModalProps) => {
  const deleteCategory = useDeleteCategory()
  const handleConfirm = $(async () => {
    deleteCategory.submit({ id: category.id })
    close()
  })

  const handleCancel = $(() => {
    close()
  })

  return (
    <Modal
      title="Usuwanie transakcji"
      subtitle={category.name}
      handleConfirm={handleConfirm}
      handleCancel={handleCancel}
    >
      <span>Czy na pewno chcesz usunąć categorię {category.name}?</span>
      <span>
        Wszystkie powiązane z nią {dataTypes[category.categoryType as CategoryType]} zostaną
        usunięte!
      </span>
    </Modal>
  )
})
