// apps/client-react/src/components/modal/ManageCategoriesModal.tsx
import Modal from './Modal'
import {
  useCreateCategoryMutation,
  useGetUsersCategoriesQuery
} from '../../redux/api/slices/categorySlice'
import { useSelector } from 'react-redux'
import { RootState } from '../../redux/store'
import React, { useEffect, useState } from 'react'
import { CategoryDTO, CategoryType } from 'shared-types'
import Button from '../buttons/Button'
import { Plus } from '../icons'
import Input from '../inputs/Input'
import Select from '../inputs/Select'
import ModalHeader from './sections/ModalHeader'
import Radio from '../inputs/Radio'
import TableHeadCell from '../table/TableHeadCell'
import CategoriesTableRow from '../table/CategoriesTableRow'

type ManageCategoriesModalProps = {
  open: boolean
  handleClose: () => void
}

const ManageCategoriesModal = ({ open, handleClose }: ManageCategoriesModalProps) => {
  const currentUser = useSelector((state: RootState) => state.currentUser.currentUser)
  const { data: categories } = useGetUsersCategoriesQuery({
    id: currentUser?.id
  })

  const [selectedTypeId, setSelectedTypeId] = useState<number | undefined>(undefined)
  const [name, setName] = useState<string | undefined>(undefined)

  const types: CategoryType[] = ['ACCOUNT', 'TRANSACTION', 'GOAL']
  const typeOptions = [
    {
      id: 0,
      name: 'Konta'
    },
    {
      id: 1,
      name: 'Transakcje'
    },
    {
      id: 2,
      name: 'Cele'
    }
  ]

  const handleTypeSelect = (e: React.ChangeEvent<HTMLSelectElement>) => {
    let id = e.target.value
    setSelectedTypeId(+id)
  }

  const [createCategory] = useCreateCategoryMutation()

  const handleAdd = () => {
    console.log(currentUser, name, selectedTypeId)
    if (currentUser && name && selectedTypeId !== undefined) {
      let type = types[selectedTypeId]
      let newCategory: Partial<CategoryDTO> = {
        user: currentUser?.id,
        categoryType: type,
        name: name
      }

      createCategory(newCategory)
      setName('')
      setSelectedTypeId(0)
    }
  }

  const [selectedType, setSelectedType] = useState<CategoryType | 'ALL'>('ACCOUNT')
  const [visibleCategories, setVisibleCategories] = useState<CategoryDTO[]>([])

  useEffect(() => {
    if (categories) {
      if (selectedType === 'ALL') {
        setVisibleCategories(categories)
        return
      }
      let filteredCategories = categories.filter((c) => c.categoryType === selectedType)
      setVisibleCategories(filteredCategories)
    }
  }, [categories, selectedType])

  return (
    <>
      {open && (
        <Modal handleClose={handleClose} width="w-fit">
          <ModalHeader handleClose={handleClose} title={'Kategorie'} />

          <div className="flex flex-col max-h-[500px] overflow-y-auto gap-6 pr-4 pb-4">
            <div className="flex flex-col gap-2">
              <h3 className="text-sm font-bold text-background-800">Rodzaj kategorii</h3>
              <div className="flex flex-row w-full gap-8">
                <Radio
                  checked={selectedType === 'ACCOUNT'}
                  value={'ACCOUNT'}
                  name={'category_type'}
                  label={'Konta'}
                  id={'account-category-type-radio'}
                  handleChange={(e) => setSelectedType(e.target.value as CategoryType)}
                />
                <Radio
                  value={'TRANSACTION'}
                  name={'category_type'}
                  label={'Transakcje'}
                  id={'transaction-category-type-radio'}
                  handleChange={(e) => setSelectedType(e.target.value as CategoryType)}
                />
                <Radio
                  value={'GOAL'}
                  name={'category_type'}
                  label={'Cele'}
                  id={'transaction-category-type-radio'}
                  handleChange={(e) => setSelectedType(e.target.value as CategoryType)}
                />
                <Radio
                  value={'ALL'}
                  name={'category_type'}
                  label={'Wszystkie'}
                  id={'all-category-type-radio'}
                  handleChange={() => setSelectedType('ALL')}
                />
              </div>
            </div>

            <div className="w-full">
              <h3 className="text-sm font-bold text-background-800">Lista kategorii</h3>
              <table className="w-full">
                <thead>
                  <tr className="border-b-2 w-full text-xs">
                    <TableHeadCell label={'#'} align="left" />
                    <TableHeadCell label={'Nazwa'} align="left" />
                    <TableHeadCell label={'Typ'} />
                    <TableHeadCell label={'Akcja'} />
                  </tr>
                </thead>

                <tbody>
                  {visibleCategories.map((c, i) => (
                    <CategoriesTableRow category={c} index={i} />
                  ))}
                </tbody>
              </table>
            </div>

            <div>
              <h3 className="text-sm font-bold text-background-800">Nowa kategorii</h3>
              <div className="flex flex-col gap-2 pt-2">
                <Input
                  value={name}
                  type={'text'}
                  placeholder={'Podaj nazwę kategorii ...'}
                  handleChange={(e) => setName(e.target.value)}
                />
                <Select
                  options={typeOptions}
                  placeholder={'Wybierz typ kategorii ...'}
                  handleSelect={handleTypeSelect}
                  value={selectedTypeId}
                />
                <div className="flex flex-row justify-center items-center w-full pt-2">
                  <Button
                    text="Dodaj kategorię"
                    onClick={handleAdd}
                    IconLeft={Plus}
                    color="primary"
                    variant="filled"
                    size="small"
                  />
                </div>
              </div>
            </div>
          </div>
        </Modal>
      )}
    </>
  )
}

export default ManageCategoriesModal

// apps/client-qwik/src/components/modal/categories/ManageCategoriesModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, useStore, $ } from '@builder.io/qwik'
import type { CategoryDTO, CategoryType } from 'shared-types'
import { Modal } from '../Modal'
import { useAddCategory, useCategories } from '~/api/categoriesAPI'
import { CategoryTableRow } from '~/components/table/CategoryTableRow'
import { Plus } from '~/icons'
import { Button } from '~/components/buttons/Button'

type TypeOption = {
  id: number
  value: CategoryType
  name: string
}

const types: TypeOption[] = [
  {
    id: 0,
    value: 'ACCOUNT',
    name: 'Konta'
  },
  {
    id: 1,
    value: 'TRANSACTION',
    name: 'Transakcje'
  },
  {
    id: 2,
    value: 'GOAL',
    name: 'Cele'
  }
]

type EditAccountModalProps = {
  close: QRL<() => void>
}

type ManageCategoriesStateType = {
  isEditCategoryModalOpen: boolean
  isDeleteCategoryModalOpen: boolean
  name: string
  categoryType: string
  selectedCategoryType: CategoryType
}

export const ManageCategoriesModal = component$(({ close }: EditAccountModalProps) => {
  const addCategory = useAddCategory()
  const categories = useCategories().value

  const state = useStore<ManageCategoriesStateType>({
    isEditCategoryModalOpen: false,
    isDeleteCategoryModalOpen: false,
    categoryType: 'ACCOUNT',
    name: '',
    selectedCategoryType: 'ACCOUNT'
  })

  const handleConfirm = $(async () => {
    const newCategory: Partial<CategoryDTO> = {
      name: state.name,
      categoryType: state.selectedCategoryType
    }
    console.log(newCategory)
    addCategory
      .submit(newCategory)
      .then((r) => console.log(r))
      .catch((e) => console.log(e))
  })

  const handleCancel = $(() => {
    close()
  })

  return (
    <>
      <Modal
        title="Zarządzanie kategoriami"
        handleConfirm={handleConfirm}
        handleCancel={handleCancel}
        footer={false}
      >
        <div class="flex flex-col gap-1">
          <h5 class="text-sm font-bold text-background-700">Rodzaj kategorii</h5>
          <div class="flex flex-row gap-6 pl-4">
            <div class="flex flex-row gap-2">
              <input
                type="radio"
                checked={state.categoryType === 'ACCOUNT'}
                id="categories-categproes"
                value="ACCOUNT"
                onInput$={(e) =>
                  (state.categoryType = (e.target as HTMLInputElement).value).toString()
                }
              />
              <label for="categories-categproes">Konta</label>
            </div>
            <div class="flex flex-row gap-2">
              <input
                type="radio"
                checked={state.categoryType === 'TRANSACTION'}
                id="transaction-categories"
                value="TRANSACTION"
                onInput$={(e) =>
                  (state.categoryType = (e.target as HTMLInputElement).value).toString()
                }
              />
              <label for="transaction-categories">Transakcje</label>
            </div>
            <div class="flex flex-row gap-2">
              <input
                type="radio"
                checked={state.categoryType === 'GOAL'}
                id="categories-goal"
                value="GOAL"
                onInput$={(e) =>
                  (state.categoryType = (e.target as HTMLInputElement).value).toString()
                }
              />
              <label for="categories-goal">Cele</label>
            </div>
            <div class="flex flex-row gap-2">
              <input
                type="radio"
                checked={state.categoryType === 'ALL'}
                id="categories-all"
                value="ALL"
                onInput$={(e) =>
                  (state.categoryType = (e.target as HTMLInputElement).value).toString()
                }
              />
              <label for="categories-all">Wszystkie</label>
            </div>
          </div>
        </div>

        <div class="h-[300px] overflow-y-auto">
          <h5 class="text-sm font-bold text-background-700">Lista kategorii</h5>

          <table>
            <thead>
              <td>#</td>
              <td>Nazwa</td>
              <td>Typ</td>
              <td>Akcja</td>
            </thead>
            <tbody>
              {categories
                .filter((c) => {
                  if (state.categoryType === 'ALL') return true

                  return c.categoryType === state.categoryType
                })
                .map((c, i) => (
                  <CategoryTableRow category={c} index={i} key={`category-table-row-${c.id}`} />
                ))}
            </tbody>
          </table>
        </div>

        <div>
          <div class="flex flex-col gap-1">
            <label for="account-name-input">Nazwa </label>
            <input
              id="account-name-input"
              type="text"
              value={state.name}
              onInput$={(e) => (state.name = (e.target as HTMLInputElement).value)}
            />
          </div>

          <div class="flex flex-col gap-1">
            <label for="account-category-select">Stan konta</label>
            <select
              value={state.selectedCategoryType}
              onChange$={(e) =>
                (state.selectedCategoryType = (e.target as HTMLSelectElement).value as CategoryType)
              }
            >
              {types.map((t) => (
                <option value={t.value} key={`category-type-select-option-${t.id}`}>
                  {t.name}
                </option>
              ))}
            </select>
          </div>

          <div class="flex flex-row w-full items-center justify-center pt-4">
            <Button color="primary" onClick={handleConfirm}>
              <Plus /> Dodaj kategorię
            </Button>
          </div>
        </div>
      </Modal>
    </>
  )
})
