// apps/client-qwik/src/components/sidebar/navigation-sidebar.tsx
import { component$ } from '@builder.io/qwik'
import { SidebarContainer } from './sidebar-container'
import { Link } from '@builder.io/qwik-city'

const NavigationSidebar = component$(() => {
  return (
    <SidebarContainer>
      <div>
        <div>Logo + nowa transakcja</div>

        <div>
          <Link href="/" class="sidebar-link">
            Strona główna
          </Link>
          <Link href="/transactions" class="sidebar-link">
            Transakcje
          </Link>
          <Link href="/transactions/expenses" class="sidebar-link">
            Wydatki
          </Link>
          <Link href="/transactions/incomes" class="sidebar-link">
            Wpływy
          </Link>
          <Link href="/goals" class="sidebar-link">
            Cele
          </Link>
          <Link href="/budgets" class="sidebar-link">
            Budżety
          </Link>
          <Link href="/reports" class="sidebar-link">
            Raporty
          </Link>
          <Link href="/accounts" class="sidebar-link">
            Konta
          </Link>
          <Link href="/profile" class="sidebar-link">
            Użytkownik
          </Link>
          <Link href="/settings" class="sidebar-link">
            Ustawienia
          </Link>
          <Link href="/help" class="sidebar-link">
            Pomoc
          </Link>
        </div>
      </div>

      <div>
        <Link href="/logged-out" class="sidebar-link">
          Wyloguj się
        </Link>
      </div>
    </SidebarContainer>
  )
})

export default NavigationSidebar

// apps/client-react/src/components/sidebar/NavigationSidebar.tsx
import SidebarContainer from './SidebarContainer'
import SidebarLink from '../links/SidebarLink'
import { SidebarLinkType, SidebarSectionType } from 'shared-types'

const SIDEBAR_LNKS: SidebarSectionType[] = [
  {
    label: 'Menu',
    links: [
      { to: '/', label: 'Strona główna' },
      {
        to: '/transactions',
        label: 'Transakcje',
        links: [
          { to: '/transactions', label: 'Wszystkie' },
          { to: '/incomes', label: 'Wpływy' },
          { to: '/expenses', label: 'Wydatki' }
        ]
      },
      { to: '/goals', label: 'Cele' },
      { to: '/budgets', label: 'Budżety' },
      { to: '/reports', label: 'Raporty' },
      { to: '/accounts', label: 'Konta' }
    ]
  },
  {
    label: 'Profil',
    links: [
      { to: '/profile', label: 'Użytkownik' },
      { to: '/settings', label: 'Ustawienia' },
      { to: '/help', label: 'Pomoc' }
    ]
  }
]

const NavigationSidebar = () => {
  return (
    <SidebarContainer side="left">
      <div>
        <div>Logo</div>
        <div>Nowa transakcja</div>
        <ul className="flex flex-col gap-2 list-none">
          {SIDEBAR_LNKS.map((s: SidebarSectionType) => {
            return (
              <div>
                <span>{s.label}</span>
                {s.links.map((l: SidebarLinkType) => (
                  <SidebarLink link={l} tabIndex={0} />
                ))}
              </div>
            )
          })}
        </ul>
      </div>
      <div>
        <button className="sidebar-button">Wyloguj się</button>
      </div>
    </SidebarContainer>
  )
}

export default NavigationSidebar
