// apps/client-qwik/src/components/modal/accounts/DeleteAccountModal.tsx
import type { QRL } from '@builder.io/qwik'
import { component$, $ } from '@builder.io/qwik'
import type { AccountDTO } from 'shared-types'
import { Modal } from '../Modal'
import { useNavigate } from '@builder.io/qwik-city'
import { useDeleteAccount } from '~/api/accountsAPI'

type DeleteAccountModalProps = {
  account: AccountDTO
  open: QRL<() => void>
  close: QRL<() => void>
}

export const DeleteAccountModal = component$(({ account, close }: DeleteAccountModalProps) => {
  const deleteAccount = useDeleteAccount()
  const nav = useNavigate()
  const handleConfirm = $(async () => {
    deleteAccount.submit().then(() => {
      nav('/accounts')
      close()
    })
  })

  const handleCancel = $(() => {
    close()
  })

  return (
    <Modal
      title="Usuwanie konta"
      subtitle={account.name}
      handleConfirm={handleConfirm}
      handleCancel={handleCancel}
    >
      Czy na pewno chcesz usunąć konto {account.name}?
    </Modal>
  )
})

// apps/client-vue/src/components/modal/account/DeleteAccountModal.vue
<script setup lang="ts">
import api from '@/services/api'
import Modal from '../Modal.vue'
import { AccountDTO } from 'shared-types'
import { router } from '@/main'

// PROPS
type DeleteAccountModalProps = {
  account: AccountDTO | undefined
}

type ModalProps = {
  isOpen: boolean
  open: () => void
  close: () => void
  refetch?: () => void
}

const props = withDefaults(defineProps<DeleteAccountModalProps & ModalProps>(), {})

// API
async function deleteAccount() {
  if (props.account) await api.accounts.deleteAccount(props.account._id)
}

// HANDLERS
async function handleConfirm() {
  deleteAccount()
  props.close()
  router.push('/accounts')
}

function handleCancel() {
  props.close()
}
</script>

<template>
  <Modal
    v-if="isOpen"
    title="Usuwanie konta"
    :subtitle="account?.name"
    :handle-confirm="handleConfirm"
    :handle-cancel="handleCancel"
  >
    <span
      >Czy na pewno chcesz usunąć konto <b>{{ account?.name }}</b
      >?</span
    >
  </Modal>
</template>
