// apps/client-qwik/src/components/sections/TextWithDescription.tsx
import { component$ } from '@builder.io/qwik'

type TextWithDescriptionProps = {
  text: string | undefined
  description: string | undefined
}

export default component$(({ text, description }: TextWithDescriptionProps) => {
  return (
    <div class="pl-4">
      <h3 class="font-semibold text-background-700">{text}</h3>
      <span class="text-background-600">{description}</span>
    </div>
  )
})

// apps/client-react/src/components/text/TextWithDescription.tsx
type TextWithDescriptionProps = {
  text: string
  description: string | undefined
}

const TextWithDescription = ({ text, description }: TextWithDescriptionProps) => {
  return (
    <div>
      <h3 className="font-semibold text-background-700">{text}</h3>
      <span className="text-background-600">{description ? description : '-'}</span>
    </div>
  )
}

export default TextWithDescription
